name: "Debian kernel"
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt update; sudo apt install -y git build-essential ncurses-dev xz-utils libssl-dev bc flex libelf-dev bison binutils
      - name: Build kernel
        run: bash build.sh
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
          with:
            name: debian-kernel
            retention-days: 7
            path: |
              *.deb
